version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: leitner-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leitner_db
      POSTGRES_USER: leitner_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: